language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
install:
  - npm install -g firebase-tools
script:
  - npm install
  - npm run build
  - npm test

after_success:
  - firebase deploy --token %FIREBASE_TOKEN
